import { useState } from "react";
import { ArrowLeft, Download, Plus, RotateCcw, Save, Trash2, Upload } from "lucide-react";
import { defaultSiteConfig, loadSiteConfig, resetSiteConfig, saveSiteConfig, SiteConfig } from "./siteConfig";
const groups=["Brand","Hero","Business","Menu","Gallery","About","Contact","Design","Advanced"] as const;
type Group=typeof groups[number];
export default function AdminPanel(){
 const [c,setC]=useState<SiteConfig>(loadSiteConfig);const [tab,setTab]=useState<Group>("Brand");const [saved,setSaved]=useState(false);
 const save=()=>{saveSiteConfig(c);setSaved(true);setTimeout(()=>setSaved(false),1500)};const patch=(k:keyof SiteConfig,v:any)=>setC(x=>({...x,[k]:v}));
 const editObj=(key:keyof SiteConfig)=>Object.entries(c[key] as Record<string,any>).map(([name,val])=><label className="admin-field" key={name}><span>{name}</span><textarea rows={String(val).length>70?3:1} value={String(val??"")} onChange={e=>patch(key,{...(c[key] as any),[name]:e.target.value})}/></label>);
 const exp=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(c,null,2)],{type:"application/json"}));a.download="food-plaza-config.json";a.click()};
 const imp=(f:File)=>{const r=new FileReader();r.onload=()=>{try{setC(JSON.parse(String(r.result)))}catch{alert("Invalid config")}};r.readAsText(f)};
 return <div className="admin-page"><header className="admin-header"><div><small>FOOD PLAZA / CONTROL ROOM</small><h1>Website Admin</h1><p>Change content, menu, media, links and visual system.</p></div><div className="admin-actions"><a className="admin-btn" href="/"><ArrowLeft size={15}/> Site</a><button className="admin-btn" onClick={exp}><Download size={15}/> Export</button><label className="admin-btn">Import <input hidden type="file" accept=".json" onChange={e=>e.target.files&&imp(e.target.files[0])}/><Upload size={15}/></label><button className="admin-btn primary" onClick={save}><Save size={15}/>{saved?"Saved":"Save changes"}</button></div></header><div className="admin-layout"><aside className="admin-tabs">{groups.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button className="danger" onClick={()=>{if(confirm("Reset all customizations?")){resetSiteConfig();setC(defaultSiteConfig)}}}><RotateCcw size={14}/> Reset</button></aside><main className="admin-main">
 {tab==="Brand"&&<Card title="Brand & navigation"><div className="admin-grid">{editObj("brand")}</div><h3>Navigation links</h3><div className="admin-grid">{editObj("nav")}</div></Card>}
 {tab==="Hero"&&<Card title="Hero content"><div className="admin-grid">{editObj("hero")}</div></Card>}
 {tab==="Business"&&<Card title="Business, ordering & location"><div className="admin-grid">{editObj("business")}</div></Card>}
 {tab==="About"&&<Card title="About section"><div className="admin-grid">{editObj("about")}</div></Card>}
 {tab==="Contact"&&<Card title="Contact section"><div className="admin-grid">{editObj("contact")}</div></Card>}
 {tab==="Design"&&<Card title="Colours"><div className="admin-grid">{Object.entries(c.design).map(([k,v])=><label className="admin-field" key={k}><span>{k}</span><div className="admin-color"><input type="color" value={v} onChange={e=>patch("design",{...c.design,[k]:e.target.value})}/><input value={v} onChange={e=>patch("design",{...c.design,[k]:e.target.value})}/></div></label>)}</div></Card>}
 {tab==="Menu"&&<Card title={"Menu manager · "+c.menuItems.length+" items"}><div className="admin-menu-list">{c.menuItems.map((it,i)=><div className="admin-menu-row" key={i}><input value={it.name} onChange={e=>{const a=[...c.menuItems];a[i]={...a[i],name:e.target.value};patch("menuItems",a)}}/><input value={it.category} onChange={e=>{const a=[...c.menuItems];a[i]={...a[i],category:e.target.value};patch("menuItems",a)}}/><input type="number" value={it.price??""} placeholder="price" onChange={e=>{const a=[...c.menuItems];a[i]={...a[i],price:e.target.value?Number(e.target.value):undefined};patch("menuItems",a)}}/><input value={it.image??""} placeholder="image URL" onChange={e=>{const a=[...c.menuItems];a[i]={...a[i],image:e.target.value};patch("menuItems",a)}}/><button onClick={()=>patch("menuItems",c.menuItems.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div>)}</div><button className="admin-add" onClick={()=>patch("menuItems",[...c.menuItems,{name:"New item",category:"Other",price:0,source:"Swiggy"}])}><Plus size={15}/> Add menu item</button></Card>}
 {tab==="Gallery"&&<Card title="Gallery images"><div className="admin-menu-list">{c.gallery.map((g,i)=><div className="admin-menu-row gallery-row" key={i}><input value={g.src} placeholder="image URL" onChange={e=>{const a=[...c.gallery];a[i]={...a[i],src:e.target.value};patch("gallery",a)}}/><input value={g.alt} placeholder="alt text" onChange={e=>{const a=[...c.gallery];a[i]={...a[i],alt:e.target.value};patch("gallery",a)}}/><button onClick={()=>patch("gallery",c.gallery.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div>)}</div><button className="admin-add" onClick={()=>patch("gallery",[...c.gallery,{src:"",alt:"Food Plaza photo"}])}><Plus size={15}/> Add image</button></Card>}
 {tab==="Advanced"&&<Card title="Backup & advanced"><p className="admin-note">The current panel stores changes in this browser's localStorage. Export the JSON to move your configuration to another browser. For a multi-user production CMS, connect this panel to a database/API.</p><pre className="admin-json">{JSON.stringify(c,null,2)}</pre></Card>}
 </main></div></div>
}
function Card(p:{title:string;children:React.ReactNode}){return <section className="admin-card"><h2>{p.title}</h2>{p.children}</section>}