import { useEffect, useState } from "react";
import { business as baseBusiness, menuItems as baseMenuItems, businessImages } from "./data";
export type SiteConfig={brand:{name:string;suffix:string};nav:{orderLabel:string;links:{label:string;href:string}[]};hero:{metaLeft:string;metaRight:string;eyebrow:string;heading:string;description:string;primaryCta:string;secondaryCta:string};business:{rating:string;hours:string;locationShort:string;address:string;orderUrl:string;mapsUrl:string;mapEmbedUrl:string;phoneUrl:string;phoneDisplay:string;whatsappUrl:string};ticker:string;about:{kicker:string;heading:string;paragraph1:string;paragraph2:string;strip1:string;strip2:string};contact:{kicker:string;heading:string;orderLabel:string;orderTitle:string;orderDescription:string;visitLabel:string;visitTitle:string;formPlaceholder:string};design:Record<string,string>;menuItems:typeof baseMenuItems;gallery:Array<{src:string;alt:string}>};
export const defaultSiteConfig:SiteConfig={brand:{name:"FOOD PLAZA",suffix:"™"},nav:{orderLabel:"Order",links:[{label:"Menu",href:"/menu"},{label:"Featured",href:"#featured"},{label:"Location",href:"#location"},{label:"About",href:"#about"},{label:"Contact",href:"#contact"}]},hero:{metaLeft:"SUPRIYA ROAD · BETTIAH",metaRight:"CHINESE · FAST FOOD · ROLLS · PIZZA",eyebrow:"YOUR LOCAL CRAVING STOP.",heading:"FOOD THAT FEELS LIKE HOME.",description:"Big flavours, familiar favourites and a menu made for sharing around Bettiah.",primaryCta:"Order online",secondaryCta:"Explore menu"},business:{rating:"4.2 · 3.6K+ Swiggy ratings",hours:baseBusiness.hours,locationShort:"Old LIC Building · near V2 Mall",address:baseBusiness.address,orderUrl:baseBusiness.orderUrl,mapsUrl:baseBusiness.mapsUrl,mapEmbedUrl:baseBusiness.mapEmbedUrl,phoneUrl:baseBusiness.phoneUrl,phoneDisplay:"+91 87896 59093",whatsappUrl:"https://wa.me/918789659093?text=Hi%20Food%20Plaza%2C%20I%20found%20you%20through%20your%20website.%20I%27d%20like%20to%20make%20an%20enquiry."},ticker:"CRAVE · SAVOR · FRIED RICE · ROLLS · PIZZA · BURGERS · CHINESE · BETTIAH · ",about:{kicker:"07 / ABOUT THE STOP",heading:"Local address. Big appetite.",paragraph1:"Food Plaza is a Supriya Road food stop in Bettiah with a broad fast-food and Indo-Chinese menu spanning rolls, fried rice, chowmein, burgers, pizza, snacks, drinks and more.",paragraph2:"The site is designed around the same energy as the place: bold layers, quick movement, food-first imagery and small interactive moments that keep the page feeling alive.",strip1:"BETTIAH",strip2:"EST. LOCAL FAVOURITE"},contact:{kicker:"08 / CONTACT",heading:"Come hungry. Leave happy.",orderLabel:"ORDER ONLINE",orderTitle:"Skip the wait.",orderDescription:"Use the current Swiggy listing for ordering and live delivery availability.",visitLabel:"CALL / VISIT",visitTitle:"Talk to the plaza.",formPlaceholder:"Booking, feedback or a question…"},design:{red:"#df3424",redDark:"#a91e16",redDeep:"#75130f",cream:"#fff8ea",yellow:"#ffd064",blue:"#72c9ee",ink:"#15110f",paper:"#f6efe2"},menuItems:baseMenuItems,gallery:[...businessImages]};
const KEY="food-plaza-site-config-v1";
export function loadSiteConfig():SiteConfig{try{const raw=localStorage.getItem(KEY);if(!raw)return defaultSiteConfig;const x=JSON.parse(raw);return {...defaultSiteConfig,...x,brand:{...defaultSiteConfig.brand,...x.brand},nav:{...defaultSiteConfig.nav,...x.nav},hero:{...defaultSiteConfig.hero,...x.hero},business:{...defaultSiteConfig.business,...x.business},about:{...defaultSiteConfig.about,...x.about},contact:{...defaultSiteConfig.contact,...x.contact},design:{...defaultSiteConfig.design,...x.design}}}catch{return defaultSiteConfig}}
export function saveSiteConfig(c:SiteConfig){localStorage.setItem(KEY,JSON.stringify(c));window.dispatchEvent(new Event("food-plaza-config"))}
export function resetSiteConfig(){localStorage.removeItem(KEY);window.dispatchEvent(new Event("food-plaza-config"))}
export function useSiteConfig(){const [c,setC]=useState(loadSiteConfig);useEffect(()=>{const fn=()=>setC(loadSiteConfig());window.addEventListener("food-plaza-config",fn);return()=>window.removeEventListener("food-plaza-config",fn)},[]);return c}
